In [1]:
import pandas as pd 
import numpy as np

In [2]:
training_set=pd.read_csv('mushroom_train.csv')
test_set=pd.read_csv('mushroom_test.csv')

In [3]:
Y_test=training_set['class']
X_test=training_set.drop('class',axis=1)

In [16]:
X_test[X_test.dtypes[(X_test.dtypes=="float64")|(X_test.dtypes=="int64")].index.values]

      radius  weight
0        215      38
1         94      43
2        244      37
3        286      82
4        110      36
5         66      23
6         11      43
7        207      25
8         60      50
9         84      47
10       385      34
11         3      43
12        59      23
13        57      36
14       151      64
15       264      23
16       183      60
17       315      40
18       298      23
19        99      26
20       782      38
21       262      23
22       129      23
23        55      23
24       115      27
25       186      23
26         7      50
27       417      46
28       226      32
29        59      36
...      ...     ...
5656      25      23
5657     178      24
5658     152      55
5659      39      23
5660       6      24
5661     425      47
5662      13      23
5663     404      23
5664      22      24
5665     178      45
5666     473      24
5667      14      24
5668     370      36
5669       1      39
5670     389      24
5671      31      50
5672     465      23
5673     428      48
5674     468      23
5675      16      23
5676      86      68
5677      27      25
5678     210      14
5679      37      23
5680     555      26
5681     184      23
5682       4      23
5683     165      23
5684      66      50
5685     157      23

[5686 rows x 2 columns]

In [25]:
X_test.dtypes[(X_test.dtypes=='int64')|(X_test.dtypes=='float64')].index.values]

array(['radius', 'weight'], dtype=object)